// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using arroyoSeco.Infrastructure.Data;

#nullable disable

namespace arroyoSeco.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221073420_FixReservaDecimalOverflow")]
    partial class FixReservaDecimalOverflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Banos")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("FotoPrincipal")
                        .HasColumnType("text");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxHuespedes")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OferenteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("numeric");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OferenteId");

                    b.ToTable("Alojamientos");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.FotoAlojamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlojamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlojamientoId");

                    b.ToTable("FotosAlojamiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlojamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("AlojamientoId");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Establecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("FotoPrincipal")
                        .HasColumnType("text");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OferenteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OferenteId");

                    b.ToTable("Establecimientos");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablecimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<int>("EstablecimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.ReservaGastronomia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablecimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MesaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstablecimientoId");

                    b.HasIndex("MesaId");

                    b.ToTable("ReservasGastronomia");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Notificaciones.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAccion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Solicitudes.SolicitudOferente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminId")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoSolicitado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estatus");

                    b.ToTable("SolicitudesOferente");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Usuarios.Oferente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroAlojamientos")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Oferentes");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Usuarios.Oferente", "Oferente")
                        .WithMany("Alojamientos")
                        .HasForeignKey("OferenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oferente");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.FotoAlojamiento", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", "Alojamiento")
                        .WithMany("Fotos")
                        .HasForeignKey("AlojamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alojamiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Reserva", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", "Alojamiento")
                        .WithMany("Reservas")
                        .HasForeignKey("AlojamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alojamiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Establecimiento", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Usuarios.Oferente", "Oferente")
                        .WithMany("Establecimientos")
                        .HasForeignKey("OferenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oferente");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Menu", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Gastronomia.Establecimiento", "Establecimiento")
                        .WithMany("Menus")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.MenuItem", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Gastronomia.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Mesa", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Gastronomia.Establecimiento", "Establecimiento")
                        .WithMany("Mesas")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.ReservaGastronomia", b =>
                {
                    b.HasOne("arroyoSeco.Domain.Entities.Gastronomia.Establecimiento", "Establecimiento")
                        .WithMany("Reservas")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("arroyoSeco.Domain.Entities.Gastronomia.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Establecimiento");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Alojamientos.Alojamiento", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Establecimiento", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Mesas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Gastronomia.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("arroyoSeco.Domain.Entities.Usuarios.Oferente", b =>
                {
                    b.Navigation("Alojamientos");

                    b.Navigation("Establecimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
